export const categories = [
  { value: "adventure", label: "Adventure & Games" },
  { value: "creative", label: "Creative Expression" },
  { value: "food", label: "Food & Drink" },
  { value: "learning", label: "Learning & Development" },
  { value: "sports", label: "Sports and Fitness" },
  { value: "volunteering", label: "Volunteering" },
];

export const activityTypes = [
  { value: "indoor", label: "Indoor" },
  { value: "outdoor", label: "Outdoor" },
  { value: "virtual", label: "Virtual" },
];

export const locationTypes = [
  { value: "provider", label: "Provider Location" },
  { value: "user", label: "User Location" },
];

export const indianStates = [
  { value: "Andhra Pradesh", label: "Andhra Pradesh" },
  { value: "Arunachal Pradesh", label: "Arunachal Pradesh" },
  { value: "Assam", label: "Assam" },
  { value: "Bihar", label: "Bihar" },
  { value: "Chhattisgarh", label: "Chhattisgarh" },
  { value: "Goa", label: "Goa" },
  { value: "Gujarat", label: "Gujarat" },
  { value: "Haryana", label: "Haryana" },
  { value: "Himachal Pradesh", label: "Himachal Pradesh" },
  { value: "Jharkhand", label: "Jharkhand" },
  { value: "Karnataka", label: "Karnataka" },
  { value: "Kerala", label: "Kerala" },
  { value: "Madhya Pradesh", label: "Madhya Pradesh" },
  { value: "Maharashtra", label: "Maharashtra" },
  { value: "Manipur", label: "Manipur" },
  { value: "Meghalaya", label: "Meghalaya" },
  { value: "Mizoram", label: "Mizoram" },
  { value: "Nagaland", label: "Nagaland" },
  { value: "Odisha", label: "Odisha" },
  { value: "Punjab", label: "Punjab" },
  { value: "Rajasthan", label: "Rajasthan" },
  { value: "Sikkim", label: "Sikkim" },
  { value: "Tamil Nadu", label: "Tamil Nadu" },
  { value: "Telangana", label: "Telangana" },
  { value: "Tripura", label: "Tripura" },
  { value: "Uttar Pradesh", label: "Uttar Pradesh" },
  { value: "Uttarakhand", label: "Uttarakhand" },
  { value: "West Bengal", label: "West Bengal" },
  {
    value: "Andaman and Nicobar Islands",
    label: "Andaman and Nicobar Islands",
  },
  { value: "Chandigarh", label: "Chandigarh" },
  {
    value: "Dadra and Nagar Haveli and Daman and Diu",
    label: "Dadra and Nagar Haveli and Daman and Diu",
  },
  { value: "Lakshadweep", label: "Lakshadweep" },
  { value: "Delhi", label: "Delhi" },
  { value: "Puducherry", label: "Puducherry" },
  { value: "Ladakh", label: "Ladakh" },
  { value: "Jammu and Kashmir", label: "Jammu and Kashmir" },
];

export const countries = [
  { value: "in", label: "India", flag: "in", dialCode: "+91", length: 10 },
  {
    value: "us",
    label: "United States",
    flag: "us",
    dialCode: "+1",
    length: 10,
  },
  {
    value: "gb",
    label: "United Kingdom",
    flag: "gb",
    dialCode: "+44",
    length: 10,
  },
  { value: "ca", label: "Canada", flag: "ca", dialCode: "+1", length: 10 },
  { value: "de", label: "Germany", flag: "de", dialCode: "+49", length: 10 },
  { value: "fr", label: "France", flag: "fr", dialCode: "+33", length: 9 },
  {
    value: "au",
    label: "Australia",
    flag: "au",
    dialCode: "+61",
    length: 9,
  },
  { value: "jp", label: "Japan", flag: "jp", dialCode: "+81", length: 10 },
  { value: "cn", label: "China", flag: "cn", dialCode: "+86", length: 11 },
  { value: "br", label: "Brazil", flag: "br", dialCode: "+55", length: 11 },
  { value: "mx", label: "Mexico", flag: "mx", dialCode: "+52", length: 10 },
  { value: "ru", label: "Russia", flag: "ru", dialCode: "+7", length: 10 },
  {
    value: "za",
    label: "South Africa",
    flag: "za",
    dialCode: "+27",
    length: 9,
  },
  {
    value: "kr",
    label: "South Korea",
    flag: "kr",
    dialCode: "+82",
    length: 10,
  },
  {
    value: "sg",
    label: "Singapore",
    flag: "sg",
    dialCode: "+65",
    length: 8,
  },
  { value: "it", label: "Italy", flag: "it", dialCode: "+39", length: 10 },
  { value: "es", label: "Spain", flag: "es", dialCode: "+34", length: 9 },
  {
    value: "nz",
    label: "New Zealand",
    flag: "nz",
    dialCode: "+64",
    length: 9,
  },
  {
    value: "sa",
    label: "Saudi Arabia",
    flag: "sa",
    dialCode: "+966",
    length: 9,
  },
  {
    value: "ae",
    label: "United Arab Emirates",
    flag: "ae",
    dialCode: "+971",
    length: 9,
  },
  {
    value: "ar",
    label: "Argentina",
    flag: "ar",
    dialCode: "+54",
    length: 10,
  },
  { value: "at", label: "Austria", flag: "at", dialCode: "+43", length: 10 },
  { value: "be", label: "Belgium", flag: "be", dialCode: "+32", length: 9 },
  { value: "cl", label: "Chile", flag: "cl", dialCode: "+56", length: 9 },
  {
    value: "cz",
    label: "Czech Republic",
    flag: "cz",
    dialCode: "+420",
    length: 9,
  },
  { value: "dk", label: "Denmark", flag: "dk", dialCode: "+45", length: 8 },
  { value: "eg", label: "Egypt", flag: "eg", dialCode: "+20", length: 10 },
  {
    value: "fi",
    label: "Finland",
    flag: "fi",
    dialCode: "+358",
    length: 10,
  },
  { value: "gr", label: "Greece", flag: "gr", dialCode: "+30", length: 10 },
  {
    value: "hk",
    label: "Hong Kong",
    flag: "hk",
    dialCode: "+852",
    length: 8,
  },
  { value: "hu", label: "Hungary", flag: "hu", dialCode: "+36", length: 9 },
  {
    value: "id",
    label: "Indonesia",
    flag: "id",
    dialCode: "+62",
    length: 11,
  },
  { value: "ie", label: "Ireland", flag: "ie", dialCode: "+353", length: 9 },
  { value: "il", label: "Israel", flag: "il", dialCode: "+972", length: 9 },
  {
    value: "my",
    label: "Malaysia",
    flag: "my",
    dialCode: "+60",
    length: 10,
  },
  {
    value: "nl",
    label: "Netherlands",
    flag: "nl",
    dialCode: "+31",
    length: 9,
  },
  { value: "no", label: "Norway", flag: "no", dialCode: "+47", length: 8 },
  { value: "pl", label: "Poland", flag: "pl", dialCode: "+48", length: 9 },
  {
    value: "pt",
    label: "Portugal",
    flag: "pt",
    dialCode: "+351",
    length: 9,
  },
  { value: "ro", label: "Romania", flag: "ro", dialCode: "+40", length: 10 },
  { value: "se", label: "Sweden", flag: "se", dialCode: "+46", length: 9 },
  {
    value: "ch",
    label: "Switzerland",
    flag: "ch",
    dialCode: "+41",
    length: 9,
  },
  { value: "tr", label: "Turkey", flag: "tr", dialCode: "+90", length: 10 },
  {
    value: "ph",
    label: "Philippines",
    flag: "ph",
    dialCode: "+63",
    length: 10,
  },
  { value: "th", label: "Thailand", flag: "th", dialCode: "+66", length: 9 },
  { value: "vn", label: "Vietnam", flag: "vn", dialCode: "+84", length: 10 },
  {
    value: "bd",
    label: "Bangladesh",
    flag: "bd",
    dialCode: "+880",
    length: 10,
  },
];
